### ISSUE TITLE
Migrate music player to Airtable and slmn.gg

### ISSUE THREAD

**Issue by JJ1898** [slmnio/slmngg-sfc#100]
Currently, the browser-based music player's playlists are done manually by SLMN, who has exclusive access to the current music system. Migrating this to Airtable and slmn.gg would allow multiple people to upload, tag, and create music groups via Airtable without relying on a single person.
Below is a screenshot of my suggested structure for music storage on Airtable.
![image](https://user-images.githubusercontent.com/19962980/150425325-3a78a282-af02-4c56-8d80-3dfd33ad3d35.png)

**Comment by slmnio** [comment]
Seems like a good skeleton to me. The track URL should probably be replaced with just an attachment so it can be fully contained in Airtable. The group should also probably be its own table since we often have tracks in multiple groups.

**Comment by JJ1898** [comment]
I suggested track URL as a way to start storing assets on a CDN or in S3 buckets since music files, especially considering how many tracks BPL has, would allow us to avoid ballooning the attachment storage we use on Airtable

**Comment by slmnio** [comment]
You're not wrong but it's probably something we should do across the site at some point with proper planning, rather than starting here
