### ISSUE TITLE
Visual Representation of who captain is for each team on contact page for each match

### ISSUE THREAD

**Issue by JLWulf** [slmnio/slmngg-sfc#119]
**Is your feature request related to a problem? Please describe.**
I have to click through to team pages to find who the captain is. 

**Describe the solution you'd like**
Some visual designation of who the captain is on the team contacts page

**Describe alternatives you've considered**
Make it easier to click through to team page, the link can be finicky at times :(

**Additional context**

**Comment by slmnio** [comment]
Should be fairly simple - can use the icons from 3f3385692b3e35d36744e1b3cd287bb3109e843e on the detailed page (crown for captains, whistle for coaches etc

For reference, the detailed page is hidden by default but is useful for staff
![image](https://user-images.githubusercontent.com/15251071/154119687-7fd6c282-5f8b-41d3-acc7-a0fb046bd0a5.png)

The composition page might also be a good place to add this to
![image](https://user-images.githubusercontent.com/15251071/154119770-8b085b8b-94e2-4730-8a7a-2660395fc66a.png)

**Comment by slmnio** [comment]
Closed in d1927aa870ee4fbe671164dd6d0badb6c3f73a2a

![image](https://user-images.githubusercontent.com/15251071/154138722-fefbbcb7-3ea3-438e-90b5-8ce3e00113e0.png)
