### ISSUE TITLE
Default Break Image no longer displays

### ISSUE THREAD

**Issue by JJ1898** [slmnio/slmngg-sfc#124]
When no Break Image is defined in Airtable, the Break scene is supposed to display the event image on its background color as shown below on an older version of the package
![image](https://user-images.githubusercontent.com/19962980/154909406-fafda91c-2de1-4113-8896-15b183d520f4.png)

Currently, this functionality is broken on dev as shown below
![image](https://user-images.githubusercontent.com/19962980/154909523-6c0ed350-0f65-490b-b4c1-0e05f2a45e34.png)
(Both screenshots are taken loading identical data from Airtable)

Additionally, this error displays on the console, which does not display on the non-dev environment
![image](https://user-images.githubusercontent.com/19962980/154909714-5f65afac-5a77-4289-b0b7-1b1f57edbc33.png)

**Comment by slmnio** [comment]
Two errors - once was wrong capitalisation on the error message there, second was the new image system wraps background images in JS/CSS format (`{ backgroundImage: "url({url})" }`) without checking if the url is null or not. Maybe something to look at - not sure if a null background image falls back nicely in CSS
