### ISSUE TITLE
Adapt to new airtable attachment policies

### ISSUE THREAD

**Issue by JJ1898** [slmnio/slmngg-sfc#149]
Airtable [implemented a breaking change](https://support.airtable.com/docs/changes-to-airtable-attachments) that prevents slmn.gg from displaying any images. In addition, mitigations will likely be needed to deal with Airtable's new expiring URLs in the long term beyond just allowing Airtable's new domain.

**Comment by slmnio** [comment]
See comments of #150 for future further actions

**Comment by JJ1898** [comment]
An update, the attachment changes also break the music player. This issue is resolved for now, but will break again come February when Airtable will force all users to their new expiring URL platform.

**Comment by zusorio** [comment]
I think all these issues were fixed
