### ISSUE TITLE
Make token copying easier for producers

### ISSUE THREAD

**Issue by slmnio** [slmnio/slmngg-sfc#173]
Producers (or observers) who want to use the SLMN.GG Companion build need to provide it with their site token to make authenticated requests. The current way to do this is using the browser console and looking at the `document.cookie` string. 

PR #172 aimed to make it easier by creating a page `/api-token` that exposes it to you with a copy button, but it seems a bit too open for me. It's a vector for phishing that we don't need to expose.

An implementation of this should:

- [ ] Only be accessible to production staff, since they're the only staff that need it right now.
- [ ] Never show the full token, either only a copy button or a smaller part of the string.
- [ ] Stress the importance of keeping it safe since it will allow authenticated requests.

I think a small button on the production dashboard that opens a modal with a button, selectable text input and some text with the warnings and usage around the token.

In the future, using a public/private key pair for something like this would be the better option - it can safely stay on the Airtable database instead of just in memory.

**Comment by zusorio** [comment]
This can be closed
