### ISSUE TITLE
Implement external Discord functions using slash commands

### ISSUE THREAD

**Issue by slmnio** [slmnio/slmngg-sfc#184]
There's currently a separate bot that runs as WrinkleBot that interfaces with the SLMN.GG Airtable to deal with webcams and user profile changes. This should be brought to this repo, possibly with some extra commands, and should use the new (not anymore) slash commands.

Commands to implement:

- [ ] /webcam - get or create a (targeted or self) user's webcam data (Live Guests)
- [ ] /detailed - get detailed match based on the text channel it is used in (Broadcasts could have Discord Control IDs)

**Comment by zusorio** [comment]
We can probably just use the [`create-live-guest`](https://github.com/slmnio/slmngg-sfc/blob/master/server/src/actions/create-live-guest.js) action for managing webcams. That way we have the same logic both on `/cams` and the bot.
