### ISSUE TITLE
Replay Ingame view

### ISSUE THREAD

**Issue by zusorio** [slmnio/slmngg-sfc#187]
For replays we've been using some custom css inside obs to modify the standard ingame overlay, removing the scores, sides, and middle text. We should make this a standard endpoint that can be used without extra css.

**Comment by slmnio** [comment]
This was actually added in https://github.com/slmnio/slmngg-sfc/commit/5e7376f03fb7752702cef8677846c15a21b0eea1

You can either use the "Use basic overlay" observer setting to force it on observers, or use parameter `basic=true` on the ingame overlay (e.g. https://dev.slmn.gg/broadcast/kitsune/ingame?basic=true)

**Comment by zusorio** [comment]
okay in my defense it's not [documented here yet](https://github.com/slmnio/slmngg-sfc/wiki/Broadcast-routes#routes-with-query-options)
