### ISSUE TITLE
The profile page layout is kinda fucked

### ISSUE THREAD

**Issue by zusorio** [slmnio/slmngg-sfc#258]
![image](https://github.com/slmnio/slmngg-sfc/assets/23165606/bad1f11c-95c1-4b85-928d-4385a0a9ef7f)

**Comment by slmnio** [comment]
Duplicate of #256 

( 🐢 )

**Comment by zusorio** [comment]
Nooooooooooooooooooooooooooooooo not the 🐢

**Comment by slmnio** [comment]
hi

**Comment by slmnio** [comment]
Duplicate of #256
