### ISSUE TITLE
Track observer feed URLs

### ISSUE THREAD

**Issue by zusorio** [slmnio/slmngg-sfc#266]
Whenever an observer uses `/srt` or `/rtmp`, we should store the receiver URL in Airtable (either on the player or client).
This would allow the companion plugin to automatically set all observer feeds in OBS, regardless of the chosen relay.

**Comment by slmnio** [comment]
Added on the companion module: https://github.com/slmnio/companion-module-slmngg/commit/1e67460237eb428698765e183af9b0cf137b33a6
