### ISSUE TITLE
Investigate custom domains for minisites

### ISSUE THREAD

**Issue by slmnio** [slmnio/slmngg-sfc#47]
Having a custom domain that acts as a minisite (bpl.slmn.gg/schedule -> bpl.gg/schedule or owlet.slmn.gg -> owlettournament.com/schedule) would be great for including other broadcasts and for branding.

This probably isn't too hard but might require a new table or record for minisites.

**Comment by somersjw** [comment]
I'll give this task a shot

**Comment by slmnio** [comment]
I think this is out of scope for now. Could be revisited in the future.
