### ISSUE TITLE
Meta tags not populating with variables from pages

### ISSUE THREAD

**Issue by cpbeaslin** [slmnio/slmngg-sfc#51]
Meta tags broke and doesn't show player name in the embed on Discord

![unknown (15)](https://user-images.githubusercontent.com/35041696/125245182-7b40dc80-e2ad-11eb-8f79-4057aa4299e5.png)

**Comment by cpbeaslin** [comment]
same thing with event pages and team pages 

![](https://cdn.discordapp.com/attachments/864039053645053972/864042882117402664/unknown.png)

**Comment by slmnio** [comment]
Can reproduce, looks like the static embed file isn't getting data from the data service. I wonder if this is from all the cors and server changes.

**Comment by slmnio** [comment]
https://github.com/slmnio/slmngg-sfc/blob/8f4cdc715adda34504ea50b6b918c17adf590118/server/src/index.js#L11

Found it - if the origin is `undefined` or `null` (which it usually is from the PHP request) then it'll throw an error here
