### ISSUE TITLE
Player List does not work

### ISSUE THREAD

**Issue by JJ1898** [slmnio/slmngg-sfc#83]
The [Player](https://slmn.gg/players) list does not load

The console on dev.slmn.gg shows this error upon loading the Player list:
![image](https://user-images.githubusercontent.com/19962980/146653071-ec0f7e8c-572a-4183-8920-792311fb1ad5.png)

**Comment by slmnio** [comment]
This is probably due to the Snowdown - someone has been creating player profiles but left one without a name. You can grab someone to fix that but this is still a bug
