### ISSUE TITLE
Implement a "Add to calendar" button on events

### ISSUE THREAD

**Issue by slmnio** [slmnio/slmngg-sfc#84]
Sometimes you just want to know when an event is held! Links to add to Google Calendar and a .ics file are probably requirements. 

With the addition of "special events" in https://github.com/slmnio/slmngg-sfc/commit/1fa741b9d4e7ca6c2355ca2c1eb02704ba2342c1 this becomes even more useful.

**Comment by ZusorCode** [comment]
Could probably use something like [this](https://www.npmjs.com/package/vue-add-to-calendar).
